'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import Textarea from '@/components/ui/Textarea';
import Badge from '@/components/ui/Badge';
import Switch from '@/components/ui/Switch';
import Dialog from '@/components/ui/Dialog';
import { getMediaUrl } from '@/lib/api';
import {
  Plus,
  Search,
  Edit,
  Trash2,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Layers,
  Star,
  Upload,
  ImageIcon,
  Sparkles
} from 'lucide-react';
import { useToast } from '@/components/ui/Toast';

export default function AdminProjectsPage() {
  const toast = useToast();
  const [projects, setProjects] = useState([]);
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);

  // Filters & Search
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [categoryFilter, setCategoryFilter] = useState('all');

  // Project Modal State
  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState('create'); // 'create' | 'edit'
  const [savingProject, setSavingProject] = useState(false);
  const [currentId, setCurrentId] = useState(null);

  const [formData, setFormData] = useState({
    title: '',
    slug: '',
    summary: '',
    description: '',
    thumbnail: '',
    gallery: '',
    techStack: '',
    category: '',
    liveUrl: '',
    repoUrl: '',
    featured: false,
    status: 'published',
    features: '',
    challenges: '',
    solutions: ''
  });

  // Category Manager Modal State
  const [categoryModalOpen, setCategoryModalOpen] = useState(false);
  const [newCategoryName, setNewCategoryName] = useState('');

  // Delete Confirmation State
  const [deleteConfirmOpen, setDeleteConfirmOpen] = useState(false);
  const [itemToDelete, setItemToDelete] = useState(null);


  const [thumbnailUploading, setThumbnailUploading] = useState(false);
  const [aiGenerating, setAiGenerating] = useState(false);

  const handleAiGenerateCaseStudy = async () => {
    if (!formData.title.trim()) return;
    setAiGenerating(true);
    try {
      const res = await api.aiGenerateCaseStudy({
        title: formData.title,
        roughNotes: formData.description || formData.summary,
        techStack: formData.techStack
      });
      if (res?.data) {
        const d = res.data;
        setFormData((prev) => ({
          ...prev,
          summary: d.summary || prev.summary,
          description: d.description || prev.description,
          features: Array.isArray(d.features) ? d.features.join('\n') : prev.features,
          challenges: Array.isArray(d.challenges) ? d.challenges.join('\n') : prev.challenges,
          solutions: Array.isArray(d.solutions) ? d.solutions.join('\n') : prev.solutions,
          techStack: d.suggestedTechStack?.length ? d.suggestedTechStack.join(', ') : prev.techStack
        }));
        toast.success('✨ Case study content generated by AI! You can edit any field before saving.');
      }
    } catch (err) {
      toast.error(err.message || 'Failed to auto-generate case study.');
    } finally {
      setAiGenerating(false);
    }
  };

  const loadData = async () => {
    setLoading(true);
    try {
      const [projRes, catRes] = await Promise.all([
        api.getProjects(),
        api.getProjectCategories()
      ]);
      if (projRes?.data) setProjects(projRes.data);
      if (catRes?.data) {
        setCategories(catRes.data);
        if (!formData.category && catRes.data.length > 0) {
          setFormData((prev) => ({ ...prev, category: catRes.data[0]._id }));
        }
      }
    } catch (err) {
      toast.error(err.message || 'Failed to load projects.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const openCreateModal = () => {
    setModalMode('create');
    setCurrentId(null);
    setFormData({
      title: '',
      slug: '',
      summary: '',
      description: '',
      thumbnail: '',
      gallery: '',
      techStack: '',
      category: categories[0]?._id || '',
      liveUrl: '',
      repoUrl: '',
      featured: false,
      status: 'published',
      features: '',
      challenges: '',
      solutions: ''
    });
    setModalOpen(true);
  };

  const openEditModal = (p) => {
    setModalMode('edit');
    setCurrentId(p._id);
    setFormData({
      title: p.title || '',
      slug: p.slug || '',
      summary: p.summary || '',
      description: p.description || '',
      thumbnail: p.thumbnail || '',
      gallery: Array.isArray(p.gallery) ? p.gallery.join('\n') : '',
      techStack: Array.isArray(p.techStack) ? p.techStack.join(', ') : '',
      category: p.category?._id || p.category || categories[0]?._id || '',
      liveUrl: p.liveUrl || '',
      repoUrl: p.repoUrl || '',
      featured: Boolean(p.featured),
      status: p.status || 'draft',
      features: Array.isArray(p.features) ? p.features.join('\n') : '',
      challenges: Array.isArray(p.challenges) ? p.challenges.join('\n') : '',
      solutions: Array.isArray(p.solutions) ? p.solutions.join('\n') : ''
    });
    setModalOpen(true);
  };

  const handleThumbnailUpload = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setThumbnailUploading(true);
    try {
      const res = await api.uploadMedia(file);
      if (res?.data?.url) {
        setFormData((prev) => ({ ...prev, thumbnail: res.data.url }));
      }
    } catch (err) {
      toast.error(err.message || 'Image upload failed.');
    } finally {
      setThumbnailUploading(false);
      // reset so the same file can be re-selected
      e.target.value = '';
    }
  };

  const handleSaveProject = async (e) => {
    e.preventDefault();
    setSavingProject(true);

    const payload = {
      ...formData,
      gallery: formData.gallery.split('\n').map((s) => s.trim()).filter(Boolean),
      techStack: formData.techStack.split(',').map((s) => s.trim()).filter(Boolean),
      features: formData.features.split('\n').map((s) => s.trim()).filter(Boolean),
      challenges: formData.challenges.split('\n').map((s) => s.trim()).filter(Boolean),
      solutions: formData.solutions.split('\n').map((s) => s.trim()).filter(Boolean)
    };

    try {
      if (modalMode === 'create') {
        const res = await api.createProject(payload);
        if (res?.data) {
          setProjects([...projects, res.data]);
          toast.success('Project created successfully!');
        }
      } else {
        const res = await api.updateProject(currentId, payload);
        if (res?.data) {
          setProjects(projects.map((p) => (p._id === currentId ? res.data : p)));
          toast.success('Project updated successfully!');
        }
      }
      setModalOpen(false);
    } catch (err) {
      toast.error(err.message || 'Error saving project.');
    } finally {
      setSavingProject(false);
    }
  };

  const handleDeleteConfirm = async () => {
    if (!itemToDelete) return;
    try {
      await api.deleteProject(itemToDelete._id);
      setProjects(projects.filter((p) => p._id !== itemToDelete._id));
      toast.success(`Deleted "${itemToDelete.title}".`);
      setDeleteConfirmOpen(false);
      setItemToDelete(null);
    } catch (err) {
      toast.error(err.message || 'Failed to delete project.');
    }
  };

  // Reordering up/down with instant MongoDB write
  const moveItem = async (index, direction) => {
    const targetIndex = index + direction;
    if (targetIndex < 0 || targetIndex >= projects.length) return;

    const updated = [...projects];
    const temp = updated[index];
    updated[index] = updated[targetIndex];
    updated[targetIndex] = temp;

    // Recalculate order values
    const itemsPayload = updated.map((item, idx) => ({
      id: item._id,
      order: idx + 1
    }));

    setProjects(updated);
    try {
      await api.reorderProjects(itemsPayload);
    } catch (err) {
      console.error('Reordering error:', err);
    }
  };

  // Category CRUD
  const handleAddCategory = async (e) => {
    e.preventDefault();
    if (!newCategoryName.trim()) return;
    try {
      const res = await api.createProjectCategory({ name: newCategoryName.trim() });
      if (res?.data) {
        setCategories([...categories, res.data]);
        setNewCategoryName('');
      }
    } catch (err) {
      toast.error(err.message || 'Failed to create category.');
    }
  };

  const handleDeleteCategory = async (catId) => {
    try {
      await api.deleteProjectCategory(catId);
      setCategories(categories.filter((c) => c._id !== catId));
    } catch (err) {
      toast.error(err.message || 'Cannot delete category.');
    }
  };

  // Filtered list
  const filteredProjects = projects.filter((p) => {
    const matchesSearch =
      !search ||
      p.title.toLowerCase().includes(search.toLowerCase()) ||
      p.summary?.toLowerCase().includes(search.toLowerCase());

    const matchesStatus = statusFilter === 'all' || p.status === statusFilter;
    const pCatId = p.category?._id || p.category;
    const matchesCategory = categoryFilter === 'all' || pCatId === categoryFilter;

    return matchesSearch && matchesStatus && matchesCategory;
  });

  return (
    <div className="space-y-8">

      {/* Header & Main Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-extrabold tracking-tight text-foreground">
            Projects & Case Studies
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Manage your public portfolio projects, live links, and full case study writeups.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Button variant="outline" size="sm" onClick={() => setCategoryModalOpen(true)} className="gap-2">
            <Layers className="h-4 w-4" />
            <span>Manage Categories</span>
          </Button>

          <Button onClick={openCreateModal} size="sm" className="gap-2 shadow-sm">
            <Plus className="h-4 w-4" />
            <span>Create Project</span>
          </Button>
        </div>
      </div>



      {/* Search and Filters Bar */}
      <div className="flex flex-col md:flex-row items-center gap-4 bg-card/60 p-4 rounded-2xl border border-border/60">
        <div className="relative flex-1 w-full">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder="Search projects by title or summary..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="pl-9"
          />
        </div>

        <div className="flex items-center gap-3 w-full md:w-auto">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="h-10 px-3 rounded-lg border border-input bg-background/60 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
          >
            <option value="all">All Statuses</option>
            <option value="published">Published Only</option>
            <option value="draft">Drafts Only</option>
          </select>

          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            className="h-10 px-3 rounded-lg border border-input bg-background/60 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
          >
            <option value="all">All Categories</option>
            {categories.map((c) => (
              <option key={c._id} value={c._id}>
                {c.name}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Projects List / Table */}
      <div className="rounded-2xl border border-border/70 bg-card/80 overflow-hidden shadow-sm">
        {loading ? (
          <div className="py-16 text-center text-xs font-mono text-muted-foreground animate-pulse">
            Loading project records...
          </div>
        ) : filteredProjects.length === 0 ? (
          <div className="py-16 text-center text-sm text-muted-foreground">
            No projects found matching your query.
          </div>
        ) : (
          <div className="divide-y divide-border/60">
            {filteredProjects.map((project, idx) => (
              <div
                key={project._id}
                className="p-4 sm:p-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:bg-secondary/30 transition-colors"
              >
                {/* Left: Reorder Buttons, Thumbnail, Title & Category */}
                <div className="flex items-center gap-4 min-w-0">
                  {/* Reorder Accessible Buttons */}
                  <div className="flex flex-col gap-1">
                    <button
                      type="button"
                      disabled={idx === 0}
                      onClick={() => moveItem(idx, -1)}
                      aria-label="Move project up"
                      className="p-1 rounded text-muted-foreground hover:text-foreground hover:bg-secondary disabled:opacity-30 disabled:pointer-events-none"
                    >
                      <ArrowUp className="h-3.5 w-3.5" />
                    </button>
                    <button
                      type="button"
                      disabled={idx === filteredProjects.length - 1}
                      onClick={() => moveItem(idx, 1)}
                      aria-label="Move project down"
                      className="p-1 rounded text-muted-foreground hover:text-foreground hover:bg-secondary disabled:opacity-30 disabled:pointer-events-none"
                    >
                      <ArrowDown className="h-3.5 w-3.5" />
                    </button>
                  </div>

                  {/* Thumbnail */}
                  <div className="w-16 h-12 rounded-lg bg-muted flex-shrink-0 overflow-hidden border border-border flex items-center justify-center">
                    {project.thumbnail ? (
                      // eslint-disable-next-line @next/next/no-img-element
                      <img src={getMediaUrl(project.thumbnail)} alt={project.title} className="w-full h-full object-cover" />
                    ) : (
                      <span className="text-[10px] font-mono text-muted-foreground">No img</span>
                    )}
                  </div>

                  {/* Info */}
                  <div className="min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h3 className="text-base font-bold text-foreground truncate">
                        {project.title}
                      </h3>
                      {project.featured && (
                        <Badge className="bg-amber-500 text-white text-[10px] px-1.5 py-0 gap-0.5">
                          <Star className="h-2.5 w-2.5 fill-current" />
                          <span>Featured</span>
                        </Badge>
                      )}
                      <Badge
                        variant={project.status === 'published' ? 'success' : 'secondary'}
                        className="text-[10px] px-1.5 py-0 capitalize"
                      >
                        {project.status}
                      </Badge>
                    </div>

                    <div className="flex items-center gap-3 text-xs text-muted-foreground mt-1">
                      <span>{project.category?.name || 'Uncategorized'}</span>
                      <span>•</span>
                      <span className="font-mono truncate max-w-[200px] sm:max-w-xs">
                        /projects/{project.slug}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Right: Actions */}
                <div className="flex items-center gap-2 self-end sm:self-center flex-shrink-0">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => openEditModal(project)}
                    className="gap-1.5 text-xs"
                  >
                    <Edit className="h-3.5 w-3.5" />
                    <span>Edit</span>
                  </Button>

                  <button
                    type="button"
                    onClick={() => {
                      setItemToDelete(project);
                      setDeleteConfirmOpen(true);
                    }}
                    aria-label={`Delete ${project.title}`}
                    className="p-2 rounded-lg text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Project Create/Edit Dialog */}
      <Dialog
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        title={modalMode === 'create' ? 'Create New Project' : 'Edit Project'}
        description="All fields are persisted to MongoDB and immediately updated on the public site."
        maxWidth="max-w-3xl"
      >
        <form onSubmit={handleSaveProject} className="space-y-4">
          {/* AI Case Study Copilot Banner */}
          <div className="p-3.5 rounded-xl bg-primary/10 border border-primary/25 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-lg bg-primary text-primary-foreground flex items-center justify-center shrink-0 shadow-sm">
                <Sparkles className="w-4 h-4" />
              </div>
              <div>
                <span className="text-xs font-bold text-foreground">AI Case Study Copilot</span>
                <p className="text-[11px] text-muted-foreground">Type a project title below, then auto-generate summary, features, and solutions</p>
              </div>
            </div>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleAiGenerateCaseStudy}
              disabled={aiGenerating || !formData.title.trim()}
              className="gap-1.5 shrink-0 border-primary/40 text-primary hover:bg-primary/10"
            >
              {aiGenerating ? (
                <>
                  <div className="w-3.5 h-3.5 rounded-full border-2 border-primary border-t-transparent animate-spin" />
                  Drafting with AI...
                </>
              ) : (
                <>
                  <Sparkles className="w-3.5 h-3.5" />
                  Auto-Draft with AI
                </>
              )}
            </Button>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                Project Title <span className="text-primary">*</span>
              </label>
              <Input
                required
                value={formData.title}
                onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                placeholder="e.g. CloudMesh Engine"
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                URL Slug (leave blank to auto-generate)
              </label>
              <Input
                value={formData.slug}
                onChange={(e) => setFormData({ ...formData, slug: e.target.value })}
                placeholder="e.g. cloudmesh-engine"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                Category <span className="text-primary">*</span>
              </label>
              <select
                value={formData.category}
                onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
                required
              >
                {categories.map((c) => (
                  <option key={c._id} value={c._id}>
                    {c.name}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                Status
              </label>
              <select
                value={formData.status}
                onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              >
                <option value="published">Published (Public)</option>
                <option value="draft">Draft (Hidden)</option>
              </select>
            </div>

            <div className="flex items-center pt-5">
              <Switch
                checked={formData.featured}
                onChange={(val) => setFormData({ ...formData, featured: val })}
                label="Featured Project"
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-muted-foreground mb-1">
              Short Summary (Cards & Previews) <span className="text-primary">*</span>
            </label>
            <Input
              required
              value={formData.summary}
              onChange={(e) => setFormData({ ...formData, summary: e.target.value })}
              placeholder="1-2 sentences summarizing the project impact."
            />
          </div>

          <div>
            <label className="block text-xs font-semibold text-muted-foreground mb-1">
              Full Case Study Description
            </label>
            <Textarea
              rows={4}
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Detailed architecture overview, methodologies, and engineering outcomes."
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                Thumbnail Image
              </label>

              {/* URL + OR + Upload row */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <Input
                  placeholder="/uploads/... or https://..."
                  value={formData.thumbnail}
                  onChange={(e) => setFormData({ ...formData, thumbnail: e.target.value })}
                  style={{ flex: 1, minWidth: 0 }}
                />

                {/* OR divider */}
                <span style={{
                  flexShrink: 0,
                  fontSize: '11px',
                  fontWeight: 600,
                  color: 'var(--muted-foreground)',
                  textTransform: 'uppercase',
                  letterSpacing: '0.05em',
                  padding: '0 2px'
                }}>or</span>

                {/* Hidden file input */}
                <input
                  id="thumbnail-file-input"
                  type="file"
                  accept="image/*"
                  style={{ display: 'none' }}
                  onChange={handleThumbnailUpload}
                />

                {/* Upload button */}
                <button
                  type="button"
                  title="Upload image from computer"
                  disabled={thumbnailUploading}
                  onClick={() => document.getElementById('thumbnail-file-input').click()}
                  style={{
                    flexShrink: 0,
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '5px',
                    padding: '6px 12px',
                    borderRadius: '8px',
                    border: '1.5px dashed var(--border)',
                    background: thumbnailUploading ? 'var(--muted)' : 'transparent',
                    color: thumbnailUploading ? 'var(--muted-foreground)' : 'var(--foreground)',
                    fontSize: '12px',
                    fontWeight: 500,
                    cursor: thumbnailUploading ? 'not-allowed' : 'pointer',
                    whiteSpace: 'nowrap',
                    transition: 'background 0.2s, border-color 0.2s'
                  }}
                  onMouseEnter={e => { if (!thumbnailUploading) e.currentTarget.style.background = 'var(--muted)'; }}
                  onMouseLeave={e => { if (!thumbnailUploading) e.currentTarget.style.background = 'transparent'; }}
                >
                  {thumbnailUploading
                    ? <><span style={{ width: 13, height: 13, border: '2px solid currentColor', borderTopColor: 'transparent', borderRadius: '50%', display: 'inline-block', animation: 'spin 0.7s linear infinite' }} />Uploading…</>
                    : <><Upload size={13} />Upload</>}
                </button>
              </div>

              {/* Preview strip */}
              {formData.thumbnail && (
                <div style={{ marginTop: 8, display: 'flex', alignItems: 'center', gap: 8 }}>
                  <img
                    src={getMediaUrl(formData.thumbnail)}
                    alt="Thumbnail preview"
                    onError={e => { e.currentTarget.style.display = 'none'; }}
                    style={{ width: 52, height: 52, objectFit: 'cover', borderRadius: 6, border: '1px solid var(--border)' }}
                  />
                  <span style={{ fontSize: 11, color: 'var(--muted-foreground)', wordBreak: 'break-all' }}>{formData.thumbnail}</span>
                </div>
              )}
            </div>

            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                Tech Stack (comma-separated)
              </label>
              <Input
                placeholder="Next.js, Node.js, Three.js, MongoDB"
                value={formData.techStack}
                onChange={(e) => setFormData({ ...formData, techStack: e.target.value })}
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                Live Demo URL
              </label>
              <Input
                placeholder="https://..."
                value={formData.liveUrl}
                onChange={(e) => setFormData({ ...formData, liveUrl: e.target.value })}
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                GitHub Repository URL
              </label>
              <Input
                placeholder="https://github.com/..."
                value={formData.repoUrl}
                onChange={(e) => setFormData({ ...formData, repoUrl: e.target.value })}
              />
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-muted-foreground mb-1">
              Key Features (One per line)
            </label>
            <Textarea
              rows={3}
              placeholder="Feature 1&#10;Feature 2&#10;Feature 3"
              value={formData.features}
              onChange={(e) => setFormData({ ...formData, features: e.target.value })}
            />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                Challenges (One per line)
              </label>
              <Textarea
                rows={3}
                placeholder="Challenge 1&#10;Challenge 2"
                value={formData.challenges}
                onChange={(e) => setFormData({ ...formData, challenges: e.target.value })}
              />
            </div>

            <div>
              <label className="block text-xs font-semibold text-muted-foreground mb-1">
                Solutions (One per line)
              </label>
              <Textarea
                rows={3}
                placeholder="Solution 1&#10;Solution 2"
                value={formData.solutions}
                onChange={(e) => setFormData({ ...formData, solutions: e.target.value })}
              />
            </div>
          </div>

          <div className="flex items-center justify-end gap-3 pt-4 border-t border-border">
            <Button type="button" variant="outline" onClick={() => setModalOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" isLoading={savingProject}>
              {modalMode === 'create' ? 'Create Project' : 'Save Changes'}
            </Button>
          </div>
        </form>
      </Dialog>

      {/* Category Manager Dialog */}
      <Dialog
        isOpen={categoryModalOpen}
        onClose={() => setCategoryModalOpen(false)}
        title="Manage Project Categories"
        description="Categories organize your projects and filter tabs on the public portfolio."
      >
        <form onSubmit={handleAddCategory} className="flex gap-2 mb-6">
          <Input
            placeholder="New Category Name (e.g. AI & Tooling)"
            value={newCategoryName}
            onChange={(e) => setNewCategoryName(e.target.value)}
          />
          <Button type="submit" className="gap-1 flex-shrink-0">
            <Plus className="h-4 w-4" />
            <span>Add</span>
          </Button>
        </form>

        <div className="space-y-2">
          {categories.map((cat) => (
            <div
              key={cat._id}
              className="flex items-center justify-between p-3 rounded-xl bg-secondary/50 border border-border"
            >
              <div>
                <span className="font-semibold text-sm text-foreground">{cat.name}</span>
                <span className="text-xs text-muted-foreground ml-2 font-mono">({cat.slug})</span>
              </div>

              <button
                type="button"
                onClick={() => handleDeleteCategory(cat._id)}
                className="p-1.5 text-muted-foreground hover:text-destructive rounded-lg transition-colors"
                title="Delete Category"
              >
                <Trash2 className="h-4 w-4" />
              </button>
            </div>
          ))}
        </div>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <Dialog
        isOpen={deleteConfirmOpen}
        onClose={() => setDeleteConfirmOpen(false)}
        title="Confirm Project Deletion"
        description={`Are you sure you want to permanently delete "${itemToDelete?.title}"? This action cannot be undone.`}
      >
        <div className="flex justify-end gap-3 pt-4">
          <Button variant="outline" onClick={() => setDeleteConfirmOpen(false)}>
            Cancel
          </Button>
          <Button variant="destructive" onClick={handleDeleteConfirm}>
            Delete Project
          </Button>
        </div>
      </Dialog>

    </div>
  );
}
